# Generated by Django 4.2.5 on 2023-09-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
